# Generated by Django 4.0.1 on 2022-01-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='shorten_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_address', to='url_shortener.shortenedurl'),
        ),
    ]
